config/routes.rb
Rails.application.routes.draw do

  resources :wildfires do
    member do
      get :download_fire_pic
    end
    collection do
      get :active_fires
    end
  end

  resources :locations do
    collection do
      get 'search'
    end
  end

  root 'welcome#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :wildfires

	Wildfire.joins(:location)

	def self.search(state_query, county_query)
  	where("state like ? AND county like ?", "%#{state_query}%", "%#{county_query}%")

	end


	# def self.joiner
	# 	Location.joins(:wildfires)
	# end

end

app/models/wildfire.rb
class Wildfire < ActiveRecord::Base
	belongs_to :location
	mount_uploader :fire_pic, FirePicsUploader

	scope :active_status, -> { where(status: "Active") }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	def index
		@locations = Location.all
	end

	def new
		@new_location = Location.new
	end

	def create
		@new_location = Location.new(location_params)
			if @new_location.save
				redirect_to locations_path
			else
				redirect_to new_location_path
			end
	end

	def search
		@search_results = Location.search(params[:search_state], params[:search_county])
	end


	def edit
		@assignee = Assignee.find(params[:id])
	end

	private
		def location_params
			params.require(:location).permit!
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end

end

app/controllers/wildfires_controller.rb
class WildfiresController < ApplicationController
	
	def index
		@wildfires = Wildfire.all
	end

	def new
		@new_wildfire = Wildfire.new
	end

	def active_fires
		@wildfires = Wildfire.active_status
	end

	def create
		@new_wildfire = Wildfire.new(wildfire_params)
			if @new_wildfire.save
				redirect_to wildfires_path
			else
				render new_wildfire_path
			end
	end

	def show
		@wildfire = Wildfire.find(params[:id])
	end

	def download_fire_pic
		@wildfire = Wildfire.find(params[:id])
		file = @wildfire.fire_pic
		send_file file.path
	end

private

	def wildfire_params
		params.require(:wildfire).permit!
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wildfires_helper.rb
module WildfiresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wildfires</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.haml
.jumbotron
	%h1 Locations	
	<a class="btn btn-primary" href="/locations" role="button">Locations home »</a>
	<a class="btn btn-primary" href="/wildfires/new" role="button">Add a wildfire »</a>

<div class="page-header">

= f.label :state
= f.text_field :state

= f.label :county
= f.text_field :county

= f.label :agency
= f.text_field :agency

= f.submit "Add Location"

</div>

app/views/locations/edit.html.haml
edit.html.haml

app/views/locations/index.html.haml
.jumbotron
	%h1 Locations	
	<a class="btn btn-primary" href="/" role="button">Wildfires home »</a>
	<a class="btn btn-primary" href="/locations/new" role="button">Add a location »</a>

<div class="container">

- @locations.each do |l|
	<div class="col-lg-2">
	<b> State:
	= l.state
	%br
	County:
	= l.county
	%br
	Agency:
	= l.agency
	%br

	%br
	%br
	</div>
</div>

<div class="container">

= form_tag(search_locations_path, method: "get") do
	= label_tag("Find a state / county:")
	= select_tag :search_state, options_for_select(Location.uniq.pluck(:state))
	= select_tag :search_county, options_for_select(Location.uniq.pluck(:county))
	= submit_tag "Search"

</div>

app/views/locations/new.html.haml
= form_for @new_location, url: locations_path do |f|
	= render "form", f: f

app/views/locations/search.html.haml
.jumbotron
	%h1 Locations
	<a class="btn btn-primary" href="/" role="button">Wildfires home »</a>
	<a class="btn btn-primary" href="/locations" role="button">Back to locations »</a>

<div class="container">
<div class="col-lg-2">
%ul
- @search_results.each do |s|
	State:
	= s.state
	%br
	County:
	= s.county
	%br
	Agency:
	= s.agency
	%ul

	- s.wildfires.each do |wf|
		Wildfire Category:
		= wf.category
		%br
		Wildfire Status:
		= wf.status
		%br
		%br
</

app/views/locations/show.html.haml
show.html.haml

app/views/locations/show_search_results.html.haml
%h1 Locations

- @new_search.each do |l|
	State:
	= l.state
	County:
	= l.county
	Agency:
	= l.agency
	%br
	%br

app/views/welcome/index.html.haml
.jumbotron
	%h1 Wildfires	

	<a class="btn btn-primary" href="/wildfires" role="button">All wildfires »</a>
	<a class="btn btn-primary" href="/locations" role="button">All locations »</a>
	<a class="btn btn-primary" href="/wildfires/active_fires" role="button">All active wildfires »</a>

app/views/wildfires/_form.html.haml
.jumbotron
	%h1 Wildfires	
	<a class="btn btn-primary" href="/" role="button">Wildfires home »</a>
	<a class="btn btn-primary" href="/wildfires/new" role="button">Add a wildfire »</a>

<div class="page-header">

= f.label :category
= f.text_field :category

= f.label :status
= f.text_field :status

= f.label :location_id
= f.text_field :location_id

= f.submit "Add Wildfire"

%br
%br

= f.file_field :fire_pic

</div>

app/views/wildfires/active_fires.html.haml
.jumbotron
	%h1 Wildfires	
	<a class="btn btn-primary" href="/" role="button">Wildfires home »</a>
	<a class="btn btn-primary" href="/wildfires/new" role="button">Add a wildfire »</a>

<div class="container">
%h3 Active Fires
- @wildfires.each do |w|
	<div class="col-lg-2">
	Category:
	= w.category
	%br
	Status:
	= w.status
	%br
	Location ID:
	= w.location_id
	%br
	%br
	</div>
</div>

app/views/wildfires/edit.html.haml
edit.html.haml

app/views/wildfires/index.html.haml
.jumbotron
	%h1 Wildfires	
	<a class="btn btn-primary" href="/" role="button">Wildfires home »</a>
	<a class="btn btn-primary" href="/wildfires/new" role="button">Add a wildfire »</a>

<div class="container">

- @wildfires.each do |w|
	<div class="col-lg-2">
	<b> Category:</b>
	<b>#{w.category}</b>
	%br
	Status:
	= w.status
	%br
	= w.location.county
	= "County," 
	= w.location.state
	%br
	<button type="button" class="btn btn-xs btn-primary">Details</button>
	- if w.fire_pic?
		<a class="btn btn-xs btn-danger" href="/wildfires/#{w.id}" role="button">Fire Pic »</a>
		
	%br
	%br
	</div>
</div>

app/views/wildfires/new.html.haml
= form_for @new_wildfire, url: wildfires_path do |f|
	= render "form", f: f

app/views/wildfires/show.html.haml
.jumbotron
	%h1 Wildfires	
	<a class="btn btn-primary" href="/" role="button">Wildfires home »</a>
	<a class="btn btn-primary" href="/wildfires/new" role="button">Add a wildfire »</a>
	<a class="btn btn-xl btn-danger" href="/wildfires/#{@wildfire.id}/download_fire_pic" role="button">Download Fire Pic »</a>
%br


.container
= image_tag @wildfire.fire_pic.url